In [ ]:
#Read pdf document and convert it into text file

import pdfplumber
import json
import string

text1 = []
with pdfplumber.open("avv12.pdf") as pdf:
    count = 174
    for i in range(count):
        first_page = pdf.pages[i]
        text = first_page.extract_text()
        text1.append(text)


with open('test.txt', 'w') as f:
    f.write(json.dumps(text1))

In [9]:
#Remove non english texts and other missing symbols from text file and create a good text file

import re
import json

with open('test.txt','r') as f:
    for line in f:
        text = re.sub(r'\\u\w{4}','',line)
        
with open('test_correct.txt', 'w') as f:
    f.write(json.dumps(text))   
    
    
with open('test_correct.txt') as f:
    atext = f.read().replace('\\n',' ')


with open('test111.txt', 'w') as f:
    f.write(json.dumps(atext))
    

with open('test111.txt') as f:
    btext = f.read().replace('\\',' ')
    
with open('test11122.txt', 'w') as h:
    h.write(json.dumps(btext))

In [10]:
#Create a list using text file which contains only some record based on our conditions and list the items

import string

f = open('test11122.txt','r')
st = ""
while 1:
    line = f.readline()
    if not line:
        break
    st += line

f.close()


start_sep='Good'
end_sep='Low'
result=[]
tmp=st.split(start_sep)
for par in tmp:
    if end_sep in par:
        result.append(par.split(end_sep)[0])



start_sep='Low'
end_sep='Nationality'
result1=[]
tmp=st.split(start_sep)
for par in tmp:
    if end_sep in par:
        result1.append(par.split(end_sep)[0])

# print(result1)

In [11]:
#Create csv file from list and make them suit for analysis

def write_to_csv(list_of_emails):
    with open('good_quality.csv', 'w') as csvfile:
        for domain in list_of_emails:
            csvfile.write(domain + '\n')

write_to_csv(result)

In [12]:
#Pandas dataframe operations to clean the given data

import pandas as pd
import numpy as np


df = pd.read_csv('good_quality.csv', header=None, sep='\n')
df = df[0].str.split(',', expand=True)
df['pesrson_name'] = df[df.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)



df.drop(df.columns.difference(['pesrson_name']), 1, inplace=True)
data = df.replace('na ', np.NaN, regex=True)
df1 =  data.dropna()
df1.reset_index(drop=True)

                                          pesrson_name
0                           quality a.k.a.: Abu-Yunus
1     quality a.k.a.:  a) Iyad al-Toubasi  b) Iyad ...
2                     quality a.k.a.: Taha al-Khuwayt
3     quality a.k.a.:  a) 'Umar al-Qatari b) 'Umar ...
4     quality a.k.a.:    a) Khattab b) Ibn al-Khattab
..                                                 ...
213   quality a.k.a.:  a)   Al-Dabachi b) Al Ammu c...
214     quality a.k.a.:  a) Al-Ustadh b) Ustadh Ahmad
215   quality a.k.a.:  a) Rahman Salim Milad b) al-...
216   quality   a.k.a.:  a) Haji Pazullah Noorzai b...
217   quality a.k.a.:  a) Qazi 'Abdallah b) Qazi Ab...

[218 rows x 1 columns]

In [13]:
#Define a function for make separate row for the string which we wants after some string 

def explode(df, lst_cols, fill_value='', preserve_index=False):
    # make sure `lst_cols` is list-alike
    if (lst_cols is not None
        and len(lst_cols) > 0
        and not isinstance(lst_cols, (list, tuple, np.ndarray, pd.Series))):
        lst_cols = [lst_cols]
    # all columns except `lst_cols`
    idx_cols = df.columns.difference(lst_cols)
    # calculate lengths of lists
    lens = df[lst_cols[0]].str.len()
    # preserve original index values    
    idx = np.repeat(df.index.values, lens)
    # create "exploded" DF
    res = (pd.DataFrame({
                col:np.repeat(df[col].values, lens)
                for col in idx_cols},
                index=idx)
             .assign(**{col:np.concatenate(df.loc[lens>0, col].values)
                            for col in lst_cols}))
    # append those rows that have empty lists
    if (lens == 0).any():
        # at least one list in cells is empty
        res = (res.append(df.loc[lens==0, idx_cols], sort=False)
                  .fillna(fill_value))
    # revert the original index order
    res = res.sort_index()
    # reset index if requested
    if not preserve_index:        
        res = res.reset_index(drop=True)
    return res

In [14]:
#Using the explode function create new rows corresponds to the string inputs

df2 = df1['pesrson_name'].str.replace(")",'xwwww')
df2 = pd.DataFrame(df2)
df3 = df2['pesrson_name'].str.replace("  axwwww ","")
df3 = pd.DataFrame(df3)

df55 = explode(df3.assign(pesrson_name=df3.pesrson_name.str.split("bxwwww")), 'pesrson_name')
df5 = explode(df55.assign(pesrson_name=df55.pesrson_name.str.split("cxwwww")), 'pesrson_name')
df6 = explode(df5.assign(pesrson_name=df5.pesrson_name.str.split("dxwwww")), 'pesrson_name')
df7 = explode(df6.assign(pesrson_name=df6.pesrson_name.str.split("exwwww")), 'pesrson_name')
df8 = explode(df7.assign(pesrson_name=df7.pesrson_name.str.split("fxwwww")), 'pesrson_name')
df9 = explode(df8.assign(pesrson_name=df8.pesrson_name.str.split("gxwwww")), 'pesrson_name')
df10 = explode(df9.assign(pesrson_name=df9.pesrson_name.str.split("hxwwww")), 'pesrson_name')
df11 = explode(df10.assign(pesrson_name=df10.pesrson_name.str.split("ixwwww")), 'pesrson_name')
df12 = explode(df11.assign(pesrson_name=df11.pesrson_name.str.split("jxwwww")), 'pesrson_name')
df13 = explode(df12.assign(pesrson_name=df12.pesrson_name.str.split("kxwwww")), 'pesrson_name')
df14 = explode(df13.assign(pesrson_name=df13.pesrson_name.str.split("lxwwww")), 'pesrson_name')
df15 = explode(df14.assign(pesrson_name=df14.pesrson_name.str.split("mxwwww")), 'pesrson_name')
df16 = explode(df15.assign(pesrson_name=df15.pesrson_name.str.split("nxwwww")), 'pesrson_name')
df17 = explode(df16.assign(pesrson_name=df16.pesrson_name.str.split("oxwwww")), 'pesrson_name')
df18 = explode(df17.assign(pesrson_name=df17.pesrson_name.str.split("pxwwww")), 'pesrson_name')

df19 = df18['pesrson_name'].str.replace("xwwww",')')
df19 = pd.DataFrame(df19)
df19['pesrson_name'] = df19['pesrson_name'].str.replace(r" \(.*\)","")
df20 = df19['pesrson_name'].str.replace("quality a.k.a.:",'')
df20 = pd.DataFrame(df20)
df21 = df20['pesrson_name'].str.replace(" quality   a.k.a.:",'')
df21 = pd.DataFrame(df21)
Good_quality_name =  df21.dropna()

In [16]:
#convert dataframe into csv 

Good_quality_name.to_csv("Good_quality_names.csv")